### ISSUE TITLE
HIGH: Instant transfer of new material to WS’s for playout.

### ISSUE THREAD

**Issue by AaronJowitt** [mairlist/rebelreq2018#13]
i.e. if a asset 14000 containing pre-recorded news is scheduled every hour on the playlist, and a new bulletin is ingested into the network DB 20 seconds before airing, then this new copy of the bulletin is what should play out on all WS’s.  I saw something odd (but can’t recall) in our testing of MAL where it did Not do that.  We added a new copy of a file, and a minute later MAL played the old copy.  We frequently take traffic/road crosses this way multiple times an hour, re-using the same asset.  They frequently arrive within 1min of airing.
--

**Comment by tweibert** [comment]
By default, mAirList "pre-buffers" (opens and caches) the next few items in the playlist, indicated by the small green checkmark next to the icon; from that moment on you cannot replace the file anymore.

Prebuffering can be disabled globally, or on a per-item basis (option "Do not prebuffer" on the Playback tab in the item properties).

**Comment by AaronJowitt** [comment]
That may explain why during some of our testing, old audio went to air despite the fact new audio had been ingested a minute before airing.  Pre-buffering is I'd imagine important to 'low lag', tight transitions on air.  I recall remeasured the segue gap "EOM market from one event to cue in marker of next event) as  a couple of milliseconds.  Nice.  We'd like to retain that. Dislike lag especially in tight formats.   Would it not be best to have a third option to prebuffer xx seconds before the end of the previous playlist item?  So we could set it to prebuffer say 10s before transition time.  Plenty of time for it to get the network file and prebuffer, but still allows the audio to be updated up to 10s before airtime.  Our in house system precued the audio of items a few seconds before airtime (in sequential automation mode),and this worked well for us.  It of course checked the metadata well before that, and refreshed that periodically (i.e. in case an audio asset was invalid and became valid or vice versa)

**Comment by tweibert** [comment]
Prebuffering x seconds before projected start time (as displayed) instead of a fixed number of items is actually a very good idea.
