### ISSUE TITLE
MEDIUM: Virtual clock offest for a specific station/playlist on a pc.

### ISSUE THREAD

**Issue by AaronJowitt** [mairlist/rebelreq2018#27]
A couple of our stations played out from the one pc are for different time zones. WO has a simple +1:00 offset we can aplly to that station config, and it puts that instances on screen clock forward by an hour and executes/playout in that time zone.  Interim workaround is have a temp 2nd  pc for that, which we are prepared to do for a year.
--

**Comment by tweibert** [comment]
mAirList as a "time correction" feature built in exactly for this purpose. Double-click clock in the status bar for manual adjustment. Can also be done automatically at startup through a script (or GUI setting for the future).
