### ISSUE TITLE
HIGH: Time Scaling algorithm audio quality

### ISSUE THREAD

**Issue by AaronJowitt** [mairlist/rebelreq2018#3]
Have not closely evaluated the BASS algorithm for artefacts, but MAL must have HQ scaling with minimal artefacts.  Many open source implementations have poor quality  i.e. Zetta/WO have HQ CPU based time scaling.
--

**Comment by tweibert** [comment]
We use the BASS_FX libary from here: http://jobnik.org/

Which in turn seems to use this library here: http://www.linuxfromscratch.org/blfs/view/8.1/multimedia/soundtouch.html

Cannot really comment on the quality as I have no experience with other libraries. Changelog says the new version 2.4.12 (released last week) uses a new version of the SoundTouch lib which should even provide higher quality. Haven't tried that new version yet.
